[build]
  publish = "build/web"
  command = "flutter build web --release"

[[plugins]]
  package = "netlify-plugin-flutter"

  [plugins.inputs]
    channel = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/flutter.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
